import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalStateProvider } from "./context/GlobalStateContext";
import { ActiveLinkProvider } from "./context/ActiveLinkContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OTOSUM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GlobalStateProvider>
        <ActiveLinkProvider>
          <body className={`${inter.className} w-full`}>{children}</body>
        </ActiveLinkProvider>
      </GlobalStateProvider>
    </html>
  );
}
